services:
  - type: web
    name: postal-card-api
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm ci
      npx prisma generate
      npm run build
    startCommand: |
      cd backend
      npx prisma migrate deploy
      node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: APP_BASE_URL
        sync: false
      - key: API_BASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postal-card-db
          property: connectionString

databases:
  - name: postal-card-db
    plan: free
    ipAllowList: []  # allow all from Render services
